apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-live-api
spec:
  replicas: 2 # what was the replicaSet providing
  selector:
    matchLabels:
      app: devops-live-api
  template: # describe the pod template
    metadata:
      labels:
        app: devops-live-api
    spec:
      containers:
      - name: devops-live-api
        image: docker.io/library/devops-live-api:1.0
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "devops-live-db"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "password"
        # Readiness -> "should Kubernetes SEND TRAFFIC to this Pod?"
        # /ready checks the DB; not ready = removed from the Service endpoints (and the Ingress)
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 2
          periodSeconds: 5
